In [ ]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT.name != "ic" and PROJECT_ROOT.parent != PROJECT_ROOT:
    PROJECT_ROOT = PROJECT_ROOT.parent
DATA_DIR = PROJECT_ROOT / "data"

In [69]:
import numpy as np
import pandas as pd
from itertools import combinations
from scipy.stats import spearmanr, chi2_contingency, kruskal

In [70]:
df1 = pd.read_csv(
    DATA_DIR / "dados_gerais_bronze1.csv",index_col=0,
    
)

In [71]:
# ---- 1) Build a robust text key (so small spacing/case differences don't break grouping)
df1 = df1.copy()
df1["text_key"] = (
    df1["full_text"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

# Ensure retweet_count numeric
df1["retweet_count"] = pd.to_numeric(df1["retweet_count"], errors="coerce").fillna(0)

# ---- 2) Compare "times tweet appears in dataframe" vs retweet_count
# If retweets were rows, a common expectation would be:
# appearances ~= retweet_count + 1  (1 original + N retweet rows)
g = (
    df1.groupby("text_key", as_index=False)
       .agg(
           appearances=("text_key", "size"),
           max_retweet_count=("retweet_count", "max"),
           mean_retweet_count=("retweet_count", "mean"),
           min_retweet_count=("retweet_count", "min"),
           sample_text=("full_text", "first"),
       )
)

g["expected_if_rows_are_retweets"] = g["max_retweet_count"] + 1
g["diff_vs_expected"] = g["appearances"] - g["expected_if_rows_are_retweets"]
g["exact_match"] = g["diff_vs_expected"] == 0
g["close_match_abs_1"] = g["diff_vs_expected"].abs() <= 1

# ---- 3) Global diagnostics
summary = {
    "unique_tweets_by_text_key": int(len(g)),
    "exact_match_count": int(g["exact_match"].sum()),
    "exact_match_pct": float((g["exact_match"].mean() * 100).round(2)),
    "close_match_abs_1_count": int(g["close_match_abs_1"].sum()),
    "close_match_abs_1_pct": float((g["close_match_abs_1"].mean() * 100).round(2)),
    "pearson_corr_appearances_vs_max_rt": float(g["appearances"].corr(g["max_retweet_count"], method="pearson")),
    "spearman_corr_appearances_vs_max_rt": float(g["appearances"].corr(g["max_retweet_count"], method="spearman")),
}

print("=== Retweet-as-row check summary ===")
for k, v in summary.items():
    print(f"{k}: {v}")

# ---- 4) Inspect strongest mismatches
print("\n=== Top mismatches (largest absolute difference) ===")
display(
    g.loc[:, ["appearances", "max_retweet_count", "expected_if_rows_are_retweets",
              "diff_vs_expected", "sample_text"]]
     .assign(abs_diff=lambda x: x["diff_vs_expected"].abs())
     .sort_values("abs_diff", ascending=False)
     .head(20)
)

# ---- 5) Optional: simple conclusion flag
if summary["exact_match_pct"] < 20:
    print("\nConclusion: retweet_count is probably NOT the number of duplicate tweet rows in this dataframe.")
else:
    print("\nConclusion: there may be partial alignment, inspect mismatches before concluding.")

=== Retweet-as-row check summary ===
unique_tweets_by_text_key: 232007
exact_match_count: 195394
exact_match_pct: 84.22
close_match_abs_1_count: 214504
close_match_abs_1_pct: 92.46
pearson_corr_appearances_vs_max_rt: 0.011621061160097658
spearman_corr_appearances_vs_max_rt: 0.06170370938240214

=== Top mismatches (largest absolute difference) ===

,appearances,max_retweet_count,expected_if_rows_are_retweets,diff_vs_expected,sample_text,abs_diff
163748,108,51557,51558,-51450,LULA NO PRIMEIRO TURNO,51450
127030,5,42070,42071,-42066,Amor à pátria é o c@ralh%! \n\nAMOR AO POVO. \...,42066
226822,1,20521,20522,-20521,|￣￣￣￣￣￣￣￣￣￣￣|\n ESTUDANTE DE \n ...,20521
189238,4,17049,17050,-17046,Na hora de votar não esqueça que Bolsonaro cor...,17046
119908,1,15667,15668,-15667,a gente: mas eu não boto uma camisa vermelha p...,15667
126414,1,14365,14366,-14365,Amanhã é Lula mas daqui a 4 anos será o Léo Pe...,14365
147384,1,12796,12797,-12796,eu decidi pelo voto útil Lula 13 e acredito q ...,12796
204817,1,11821,11822,-11821,"pra quem chorou com o golpe na DILMA, com a pr...",11821
180333,1,11803,11804,-11803,lula pulando q nem uma britadeira e o alckmin ...,11803
146219,1,10613,10614,-10613,Estamos combinados: o ex-presidiário ganha nas...,10613
161468,1,10210,10211,-10210,lula assistindo taehyung cantar b0lson4aro é l...,10210
2175,1,10064,10065,-10064,- A Espanha também está com Bolsonaro. O deput...,10064
152029,1,9861,9862,-9861,FIM DO MUNDO! Aliança de Bolsonaro pediu ao TS...,9861
211540,1,9720,9721,-9720,se o lula ganhar no primeiro turno e vou virar...,9720
206131,1,9405,9406,-9405,quando a geração que vota no lula descobrir qu...,9405
131926,1,8446,8447,-8446,Bolsonaro pediu ao TSE para desobrigar a ofert...,8446
189236,1,8357,8358,-8357,Na hora de votar não esqueça que a eleição é e...,8357
122492,1,8285,8286,-8285,acho engraçado vocês falando que vão votar no ...,8285
206233,1,7623,7624,-7623,"Quando Lula ganhar e se tornar presidente, a g...",7623
220379,1,7486,7487,-7486,Um relato de quem teve que fugir da Nicarágua....,7486

Conclusion: there may be partial alignment, inspect mismatches before concluding.

In [72]:
df2 = pd.read_csv(DATA_DIR / "tweets_brutos_bronze2.csv", index_col=0)

In [73]:
df2.head()

                                           full_text
0  se o lula ganhar eu quero uma roda de beijo co...
1                    @ixslorena LULA PRESIDENTE HOJE
2        mãe morrendo de alegria na carreata do Lula
3  @trajaza AVISA QUE MEU PAI LULA VAI GANHAR PRI...
4  @indieoffw O RJ elegendo castro e juram que va...

In [74]:
len(df2)

270301

In [75]:
df3 = pd.read_parquet(DATA_DIR / "tweets_base_normalizados.parquet",)

In [76]:
df3.head()

,full_text,clean_text
0,se o lula ganhar eu quero uma roda de beijo co...,se o lula ganhar eu quero uma roda de beijo co...
1,@ixslorena LULA PRESIDENTE HOJE,@USER LULA PRESIDENTE HOJE
2,mãe morrendo de alegria na carreata do Lula,mãe morrendo de alegria na carreata do Lula
3,@trajaza AVISA QUE MEU PAI LULA VAI GANHAR PRI...,@USER AVISA QUE MEU PAI LULA VAI GANHAR PRIMEI...
4,@indieoffw O RJ elegendo castro e juram que va...,@USER O RJ elegendo castro e juram que vai dar...

In [77]:
len(df3)

192954

In [18]:
df4 = pd.read_parquet(DATA_DIR / "tweets_192k_labeled.parquet",)

In [19]:
df4.head()

,full_text,clean_text,unsupervised_sentiment
0,se o lula ganhar eu quero uma roda de beijo co...,se o lula ganhar eu quero uma roda de beijo co...,1.0
1,@ixslorena LULA PRESIDENTE HOJE,@USER LULA PRESIDENTE HOJE,0.0
2,mãe morrendo de alegria na carreata do Lula,mãe morrendo de alegria na carreata do Lula,0.0
3,@trajaza AVISA QUE MEU PAI LULA VAI GANHAR PRI...,@USER AVISA QUE MEU PAI LULA VAI GANHAR PRIMEI...,0.0
4,@indieoffw O RJ elegendo castro e juram que va...,@USER O RJ elegendo castro e juram que vai dar...,0.0

In [20]:
# 1) Validate minimum columns
required_df = {"user_id", "full_text"}
required_df2 = {"full_text"}
required_df3_any = {"full_text"}  # + clean_text-like column checked below

In [21]:
for name, frame, req in [("df", df, required_df), ("df2", df2, required_df2), ("df3", df3, required_df3_any)]:
    missing = req - set(frame.columns)
    if missing:
        raise ValueError(f"{name} missing columns: {sorted(missing)}")

In [22]:
d1 = df.copy().reset_index(drop=True)
d2 = df2.copy()
d3 = df3.copy()

In [23]:
def text_key(s: pd.Series) -> pd.Series:
    return (
        s.astype(str)
         .str.strip()
         .str.lower()
         .str.replace(r"\s+", " ", regex=True)
    )

In [24]:
d1["_text_key"] = text_key(d1["full_text"])
d2["_text_key"] = text_key(d2["full_text"])
d3["_text_key"] = text_key(d3["full_text"])

In [25]:
# 4) Create tweet_id (if not already present)
if "tweet_id" not in d1.columns:
    d1["tweet_id"] = "tw_" + (d1.index + 1).astype(str).str.zfill(9)

In [29]:
# 5) Prepare safe merge tables (avoid row explosion)
d2_stats = d2.groupby("_text_key", as_index=False).size().rename(columns={"size": "count_in_df2"})
d3_map = d3[["_text_key", 'clean_text']].drop_duplicates(subset=["_text_key"]).rename(columns={'clean_text': "clean_text"})

In [32]:
# 6) Build master table
master = (
    d1
    .merge(d2_stats, on="_text_key", how="left")
    .merge(d3_map, on="_text_key", how="left")
)

master["count_in_df2"] = master["count_in_df2"].fillna(0).astype(int)
master["in_df2"] = master["count_in_df2"] > 0

In [33]:
priority = ["tweet_id", "user_id", "screen_name", "location", "created_at", "full_text", "clean_text", "in_df2", "count_in_df2"]
priority = [c for c in priority if c in master.columns]
master = master[priority + [c for c in master.columns if c not in priority]]

In [34]:
# 8) Quick checks
print("master rows:", len(master), "| expected:", len(df))
print("tweet_id unique:", master["tweet_id"].nunique(), "| expected:", len(master))
print("missing clean_text:", int(master["clean_text"].isna().sum()))

master rows: 270301 | expected: 270301
tweet_id unique: 270301 | expected: 270301
missing clean_text: 59808

In [35]:
master.head(3)

,tweet_id,user_id,screen_name,location,created_at,full_text,clean_text,in_df2,count_in_df2,name,followers_count,retweet_count,favorite_count,lang,hashtags,source,_text_key
0,tw_000000001,772193576,pauloisfab,"Sao Paulo, Brazil",Sat Oct 01 23:59:59 +0000 2022,se o lula ganhar eu quero uma roda de beijo co...,se o lula ganhar eu quero uma roda de beijo co...,True,1,paulo rouge,439,0,0,pt,[],Twitter for iPhone,se o lula ganhar eu quero uma roda de beijo co...
1,tw_000000002,1546155973051662336,jorgehen_pr,NaN,Sat Oct 01 23:59:59 +0000 2022,@ixslorena LULA PRESIDENTE HOJE,@USER LULA PRESIDENTE HOJE,True,1,quem me conhece sabe 🚩,27,0,0,pt,[],Twitter for Android,@ixslorena lula presidente hoje
2,tw_000000003,1515570566736003072,aanandaaluz,pqp,Sat Oct 01 23:59:59 +0000 2022,mãe morrendo de alegria na carreata do Lula,mãe morrendo de alegria na carreata do Lula,True,1,Ananda,14,0,3,pt,[],Twitter for Android,mãe morrendo de alegria na carreata do lula

In [52]:
def cramers_v_bias_corrected(confusion_matrix: pd.DataFrame) -> float:
    chi2 = chi2_contingency(confusion_matrix, correction=False)[0]
    n = confusion_matrix.to_numpy().sum()
    if n == 0:
        return np.nan
    r, k = confusion_matrix.shape
    phi2 = chi2 / n
    phi2corr = max(0, phi2 - ((k - 1) * (r - 1)) / max(n - 1, 1))
    rcorr = r - ((r - 1) ** 2) / max(n - 1, 1)
    kcorr = k - ((k - 1) ** 2) / max(n - 1, 1)
    denom = max(min(kcorr - 1, rcorr - 1), 1e-12)
    return np.sqrt(phi2corr / denom)

In [53]:
def _reduce_cat(s: pd.Series, top_n: int = 20) -> pd.Series:
    s = s.astype("object").where(~pd.isna(s), "__MISSING__")
    keep = set(s.value_counts(dropna=False).head(top_n).index)
    return s.where(s.isin(keep), "__OTHER__")

In [54]:
def relation_scan(
    df: pd.DataFrame,
    force_cats=("location",),
    drop_cols=("full_text", "clean_text", "_text_key"),
    top_n_categories=20,
    min_n=30,
    min_group_size=20
):
    data = df.copy()
    data = data[[c for c in data.columns if c not in set(drop_cols)]]

    # Skip ID-like columns by default (unless forced)
    id_like = [c for c in data.columns if c.lower().endswith("_id") or c.lower() in {"id", "tweet_id"}]
    id_like = [c for c in id_like if c not in force_cats]

    numeric, categorical, skipped = [], [], []

    for c in data.columns:
        if c in id_like:
            skipped.append((c, "id_like"))
            continue

        s = data[c]
        if pd.api.types.is_bool_dtype(s):
            data[c] = s.astype(int)
            numeric.append(c)
        elif pd.api.types.is_numeric_dtype(s):
            if s.nunique(dropna=True) >= 2:
                numeric.append(c)
            else:
                skipped.append((c, "constant_numeric"))
        else:
            if s.nunique(dropna=True) >= 2 or c in force_cats:
                categorical.append(c)
            else:
                skipped.append((c, "constant_categorical"))

    for fc in force_cats:
        if fc in data.columns and fc not in categorical and fc not in numeric:
            categorical.append(fc)

    cat_reduced = {c: _reduce_cat(data[c], top_n=top_n_categories) for c in categorical}
    results = []

    # num-num
    for a, b in combinations(numeric, 2):
        tmp = data[[a, b]].dropna()
        if len(tmp) < min_n or tmp[a].nunique() < 2 or tmp[b].nunique() < 2:
            continue
        rho, p = spearmanr(tmp[a], tmp[b])
        if np.isnan(rho):
            continue
        results.append({
            "var1": a, "var2": b, "type": "num-num",
            "metric": "spearman_rho",
            "strength": float(rho), "abs_strength": abs(float(rho)),
            "p_value": float(p), "n": len(tmp)
        })

    # cat-cat
    for a, b in combinations(categorical, 2):
        tmp = pd.DataFrame({a: cat_reduced[a], b: cat_reduced[b]}).dropna()
        if len(tmp) < min_n:
            continue
        ct = pd.crosstab(tmp[a], tmp[b])
        if ct.shape[0] < 2 or ct.shape[1] < 2:
            continue
        _, p, _, _ = chi2_contingency(ct, correction=False)
        v = cramers_v_bias_corrected(ct)
        results.append({
            "var1": a, "var2": b, "type": "cat-cat",
            "metric": "cramers_v",
            "strength": float(v), "abs_strength": abs(float(v)),
            "p_value": float(p), "n": len(tmp)
        })

    # num-cat
    for ncol in numeric:
        for ccol in categorical:
            tmp = pd.DataFrame({ncol: data[ncol], ccol: cat_reduced[ccol]}).dropna()
            if len(tmp) < min_n:
                continue

            group_sizes = tmp[ccol].value_counts()
            valid_levels = group_sizes[group_sizes >= min_group_size].index
            tmp = tmp[tmp[ccol].isin(valid_levels)]
            if tmp[ccol].nunique() < 2:
                continue

            if tmp[ncol].nunique() < 2:
                continue

            groups = [g[ncol].values for _, g in tmp.groupby(ccol)]
            groups = [g for g in groups if len(g) > 0]
            if len(groups) < 2:
                continue

            all_vals = np.concatenate(groups)
            if pd.Series(all_vals).nunique() < 2:
                continue

            try:
                H, p = kruskal(*groups)
            except ValueError:
                continue

            n, k = len(tmp), len(groups)
            eps2 = max(0.0, (H - k + 1) / max(n - k, 1))
            results.append({
                "var1": ncol, "var2": ccol, "type": "num-cat",
                "metric": "kruskal_eps2",
                "strength": float(eps2), "abs_strength": abs(float(eps2)),
                "p_value": float(p), "n": n
            })

    out = pd.DataFrame(results)
    if not out.empty:
        out = out.sort_values("p_value").reset_index(drop=True)
        m = len(out)
        out["rank"] = np.arange(1, m + 1)
        out["q_value_bh"] = (out["p_value"] * m / out["rank"]).clip(upper=1.0)
        out["significant_0_05"] = out["q_value_bh"] < 0.05
        out = out.sort_values(
            ["significant_0_05", "abs_strength", "q_value_bh"],
            ascending=[False, False, True]
        ).reset_index(drop=True)

    coverage = {
        "numeric_used": numeric,
        "categorical_used": categorical,
        "skipped": pd.DataFrame(skipped, columns=["column", "reason"]),
        "type_counts": out["type"].value_counts().to_dict() if not out.empty else {}
    }

    return out, coverage

In [55]:
scan, coverage = relation_scan(master, force_cats=("location", "lang", "source", "hashtags"))
display(pd.Series(coverage["type_counts"], name="count"))
display(pd.DataFrame({"numeric_used": pd.Series(coverage["numeric_used"]),
                      "categorical_used": pd.Series(coverage["categorical_used"])}))
display(coverage["skipped"])
display(scan.head(50))

num-cat    24
cat-cat    15
num-num     6
Name: count, dtype: int64

      numeric_used categorical_used
0           in_df2      screen_name
1     count_in_df2         location
2  followers_count       created_at
3    retweet_count             name
4   favorite_count             lang
5              NaN         hashtags
6              NaN           source

     column   reason
0  tweet_id  id_like
1   user_id  id_like

,var1,var2,type,metric,strength,abs_strength,p_value,n,rank,q_value_bh,significant_0_05
0,screen_name,name,cat-cat,cramers_v,0.863259,0.863259,0.000000e+00,270301,22,0.000000e+00,True
1,retweet_count,favorite_count,num-num,spearman_rho,0.490739,0.490739,0.000000e+00,270301,21,0.000000e+00,True
2,followers_count,favorite_count,num-num,spearman_rho,0.349173,0.349173,0.000000e+00,270301,20,0.000000e+00,True
3,followers_count,retweet_count,num-num,spearman_rho,0.269221,0.269221,0.000000e+00,270301,19,0.000000e+00,True
4,screen_name,location,cat-cat,cramers_v,0.162453,0.162453,0.000000e+00,270301,17,0.000000e+00,True
5,location,name,cat-cat,cramers_v,0.141926,0.141926,0.000000e+00,270301,27,0.000000e+00,True
6,count_in_df2,favorite_count,num-num,spearman_rho,-0.133122,0.133122,0.000000e+00,270301,18,0.000000e+00,True
7,count_in_df2,followers_count,num-num,spearman_rho,-0.121935,0.121935,0.000000e+00,270301,1,0.000000e+00,True
8,screen_name,source,cat-cat,cramers_v,0.096210,0.096210,0.000000e+00,270301,24,0.000000e+00,True
9,name,source,cat-cat,cramers_v,0.095282,0.095282,0.000000e+00,270301,14,0.000000e+00,True
10,followers_count,location,num-cat,kruskal_eps2,0.087132,0.087132,0.000000e+00,270301,8,0.000000e+00,True
11,location,hashtags,cat-cat,cramers_v,0.072444,0.072444,0.000000e+00,270301,28,0.000000e+00,True
12,count_in_df2,retweet_count,num-num,spearman_rho,-0.060349,0.060349,1.766486e-216,270301,30,2.649730e-216,True
13,name,hashtags,cat-cat,cramers_v,0.057001,0.057001,0.000000e+00,270301,15,0.000000e+00,True
14,location,source,cat-cat,cramers_v,0.043947,0.043947,0.000000e+00,270301,26,0.000000e+00,True
15,screen_name,hashtags,cat-cat,cramers_v,0.041318,0.041318,0.000000e+00,270301,23,0.000000e+00,True
16,hashtags,source,cat-cat,cramers_v,0.034300,0.034300,0.000000e+00,270301,13,0.000000e+00,True
17,count_in_df2,screen_name,num-cat,kruskal_eps2,0.032010,0.032010,0.000000e+00,270301,12,0.000000e+00,True
18,count_in_df2,name,num-cat,kruskal_eps2,0.030515,0.030515,0.000000e+00,270301,11,0.000000e+00,True
19,followers_count,screen_name,num-cat,kruskal_eps2,0.015376,0.015376,0.000000e+00,270301,9,0.000000e+00,True
20,followers_count,name,num-cat,kruskal_eps2,0.013480,0.013480,0.000000e+00,270301,7,0.000000e+00,True
21,favorite_count,location,num-cat,kruskal_eps2,0.013003,0.013003,0.000000e+00,270301,2,0.000000e+00,True
22,followers_count,source,num-cat,kruskal_eps2,0.009238,0.009238,0.000000e+00,270301,5,0.000000e+00,True
23,count_in_df2,hashtags,num-cat,kruskal_eps2,0.008518,0.008518,0.000000e+00,270301,10,0.000000e+00,True
24,favorite_count,source,num-cat,kruskal_eps2,0.008221,0.008221,0.000000e+00,270301,25,0.000000e+00,True
25,retweet_count,hashtags,num-cat,kruskal_eps2,0.007877,0.007877,0.000000e+00,270301,4,0.000000e+00,True
26,count_in_df2,location,num-cat,kruskal_eps2,0.007249,0.007249,0.000000e+00,270301,16,0.000000e+00,True
27,followers_count,hashtags,num-cat,kruskal_eps2,0.006537,0.006537,0.000000e+00,270301,6,0.000000e+00,True
28,created_at,name,cat-cat,cramers_v,0.006261,0.006261,4.229650e-11,270301,37,5.144169e-11,True
29,retweet_count,source,num-cat,kruskal_eps2,0.005797,0.005797,0.000000e+00,270301,3,0.000000e+00,True
30,retweet_count,location,num-cat,kruskal_eps2,0.004983,0.004983,1.448116e-277,270301,29,2.247076e-277,True
31,count_in_df2,source,num-cat,kruskal_eps2,0.003508,0.003508,2.272839e-192,270301,31,3.299283e-192,True
32,favorite_count,name,num-cat,kruskal_eps2,0.003387,0.003387,2.193278e-185,270301,32,3.084297e-185,True
33,favorite_count,screen_name,num-cat,kruskal_eps2,0.003274,0.003274,7.173527e-179,270301,33,9.782082e-179,True
34,favorite_count,hashtags,num-cat,kruskal_eps2,0.001109,0.001109,7.555816e-56,270301,34,1.000035e-55,True
35,retweet_count,name,num-cat,kruskal_eps2,0.001023,0.001023,3.986604e-51,270301,35,5.125634e-51,True
36,retweet_count,screen_name,num-cat,kruskal_eps2,0.001015,0.001015,1.088732e-50,270301,36,1.360915e-50,True
37,retweet_count,created_at,num-cat,kruskal_eps2,0.000120,0.000120,1.015419e-04,270301,38,1.202470e-04,True
38,followers_count,created_at,num-cat,kruskal_eps2,0.000072,0.000072,6.038248e-03,270301,39,6.967210e-03,True
39,favorite_count,created_at,num-cat,kruskal_eps2,0.000063,0.000063,1.168290e-02,270301,40,1.314326e-02,True
40,screen_name,created_at,cat-cat,cramers_v,0.002905,0.002905,5.717867e-02,270301,41,6.275708e-02,False
41,location,created_at,cat-cat,cramers_v,0.001482,0.001482,3.302515e-01,270301,42,3.538409e-01,False
42,created_at,source,cat-cat,cramers_v,0.000000,0.000000,8.958876e-01,270301,43,9.375568e-01,False
43,count_in_df2,created_at,num-cat,kruskal_eps2,0.000000,0.000000,9.674266e-01,270301,44,9.894136e-01,False
44,created_at,hashtags,cat-cat,cramers_v,0.000000,0.000000,9.999997e-01,270301,45,9.999997e-01,False

In [56]:
scan[(scan["type"]=="num-cat") & (scan["var1"]=="retweet_count") & (scan["var2"]=="location")]

,var1,var2,type,metric,strength,abs_strength,p_value,n,rank,q_value_bh,significant_0_05
30,retweet_count,location,num-cat,kruskal_eps2,0.004983,0.004983,1.448116e-277,270301,29,2.247076e-277,True

In [68]:
# 1) Detect clean text column in df3
clean_col_candidates = ["clean_text", "normalized_text", "text_clean"]
clean_col = next((c for c in clean_col_candidates if c in df3.columns), None)
if clean_col is None:
    raise ValueError(f"df3 must contain one of: {clean_col_candidates}")

# 2) Normalize merge key
def _text_key(s: pd.Series) -> pd.Series:
    return (
        s.astype(str)
         .str.strip()
         .str.lower()
         .str.replace(r"\s+", " ", regex=True)
    )

d1 = df1.copy()
d3 = df3.copy()

d1["_text_key"] = _text_key(d1["full_text"])
d3["_text_key"] = _text_key(d3["full_text"])

# 3) Guarantee unique tweets on df3 side (already expected, but safe)
d3_unique = d3.drop_duplicates(subset=["_text_key"]).copy()

# 4) Merge metadata (df1) + normalized text (df3)
master_nodup = d1.merge(
    d3_unique[["_text_key", clean_col]],
    on="_text_key",
    how="inner"   # keep only tweets present in df3 unique base
).rename(columns={clean_col: "clean_text"})

# 5) Enforce one row per unique tweet after merge
master_nodup = (
    master_nodup
    .drop_duplicates(subset=["_text_key"], keep="first")
    .reset_index(drop=True)
)

# 6) Add tweet_id if missing
if "tweet_id" not in master_nodup.columns:
    master_nodup["tweet_id"] = "tw_" + (master_nodup.index + 1).astype(str).str.zfill(9)

# 7) Quick validation
print("rows:", len(master_nodup))
print("unique _text_key:", master_nodup["_text_key"].nunique())
print("duplicates by _text_key:", master_nodup.duplicated(subset=["_text_key"]).sum())

master_nodup.head(50)

rows: 192399
unique _text_key: 192399
duplicates by _text_key: 0

,user_id,screen_name,name,location,followers_count,created_at,full_text,retweet_count,favorite_count,lang,hashtags,source,_text_key,clean_text,tweet_id
0,772193576,pauloisfab,paulo rouge,"Sao Paulo, Brazil",439,Sat Oct 01 23:59:59 +0000 2022,se o lula ganhar eu quero uma roda de beijo co...,0,0,pt,[],Twitter for iPhone,se o lula ganhar eu quero uma roda de beijo co...,se o lula ganhar eu quero uma roda de beijo co...,tw_000000001
1,1546155973051662336,jorgehen_pr,quem me conhece sabe 🚩,NaN,27,Sat Oct 01 23:59:59 +0000 2022,@ixslorena LULA PRESIDENTE HOJE,0,0,pt,[],Twitter for Android,@ixslorena lula presidente hoje,@USER LULA PRESIDENTE HOJE,tw_000000002
2,1515570566736003072,aanandaaluz,Ananda,pqp,14,Sat Oct 01 23:59:59 +0000 2022,mãe morrendo de alegria na carreata do Lula,0,3,pt,[],Twitter for Android,mãe morrendo de alegria na carreata do lula,mãe morrendo de alegria na carreata do Lula,tw_000000003
3,1449859889589899264,lyeroses,sasa៹ 13 ⭐🚩,only blink,4973,Sat Oct 01 23:59:59 +0000 2022,@trajaza AVISA QUE MEU PAI LULA VAI GANHAR PRI...,0,3,pt,[],Twitter for Android,@trajaza avisa que meu pai lula vai ganhar pri...,@USER AVISA QUE MEU PAI LULA VAI GANHAR PRIMEI...,tw_000000004
4,1304397938131599361,HIGH_G_LUIZ,łu¡z 🪐,IZ*ONE,422,Sat Oct 01 23:59:59 +0000 2022,@indieoffw O RJ elegendo castro e juram que va...,0,0,pt,[],Twitter for Android,@indieoffw o rj elegendo castro e juram que va...,@USER O RJ elegendo castro e juram que vai dar...,tw_000000005
5,1564043448172306433,analourdesfn,Ana Lourdes,"Juazeiro do Norte, Brasil",53,Sat Oct 01 23:59:59 +0000 2022,LULA PRESIDENTE AMANHÃ 1️⃣3️⃣🚩❤ https://t.co/T...,1,4,pt,[],Twitter for Android,lula presidente amanhã 1️⃣3️⃣🚩❤ https://t.co/t...,LULA PRESIDENTE AMANHÃ 1️⃣3️⃣ :bandeira_triang...,tw_000000006
6,381204823,alex_paranaense,alex 1️⃣2️⃣,NaN,322,Sat Oct 01 23:59:59 +0000 2022,@DiRamaciotti Bora de Ciro está em terceiro lu...,0,3,pt,[],Twitter for Android,@diramaciotti bora de ciro está em terceiro lu...,@USER Bora de Ciro está em terceiro lugar e se...,tw_000000007
7,1262950474648563713,HellendaRochaV1,hellenzinha ⭐️,Santa Catarina,372,Sat Oct 01 23:59:59 +0000 2022,@denisoon_ Meus primos que nunca trabalharam n...,0,0,pt,[],Twitter for iPhone,@denisoon_ meus primos que nunca trabalharam n...,@USER Meus primos que nunca trabalharam na vid...,tw_000000008
8,1087515836955443200,quarentener_,eu sou tao galera,"Curitiba, Brazil",147,Sat Oct 01 23:59:59 +0000 2022,Se o Lula realmente ganhar no primeiro turno e...,0,4,pt,[],Twitter for Android,se o lula realmente ganhar no primeiro turno e...,Se o Lula realmente ganhar no primeiro turno e...,tw_000000009
9,1084139131385626627,cj_mayanasilva,Mayana Silva,NaN,22,Sat Oct 01 23:59:59 +0000 2022,@GuilhermeBoulos Lula 13❤️❤️❤️,0,0,pt,[],Twitter for iPhone,@guilhermeboulos lula 13❤️❤️❤️,@USER Lula 13 :coração_vermelho: :coração_verm...,tw_000000010
10,228536447,masquem,Igor R.B.,NaN,182,Sat Oct 01 23:59:59 +0000 2022,"LULA PRESIDENTE AMANHÃ?\n\nSE sim, segunda é d...",4,14,pt,[],Twitter Web App,"lula presidente amanhã? se sim, segunda é dia ...","LULA PRESIDENTE AMANHÃ ? SE sim , segunda é di...",tw_000000011
11,441085435,AnaCaiafa,Ana Tereza Caiafa,BH,10,Sat Oct 01 23:59:58 +0000 2022,@Damadeferroofic LULA PRESIDENTE AMANHÃ,1,3,pt,[],Twitter for iPhone,@damadeferroofic lula presidente amanhã,@USER LULA PRESIDENTE AMANHÃ,tw_000000012
12,1257092249449570305,gilleite9,gil leite 🚩🚩🚩🚩,"São Paulo, Brasil",4664,Sat Oct 01 23:59:58 +0000 2022,LULA PRESIDENTE AMANHÃ https://t.co/Hr5yPZ5FW2,1,2,pt,[],Twitter for Android,lula presidente amanhã https://t.co/hr5ypz5fw2,LULA PRESIDENTE AMANHÃ HTTPURL,tw_000000013
13,906354649409695744,gabrireIx,gabri,ela/dela,133,Sat Oct 01 23:59:58 +0000 2022,nossa o lula com mais intenção de voto no ms d...,0,0,pt,[],Twitter for iPhone,nossa o lula com mais intenção de voto no ms d...,nossa o lula com mais intenção de voto no ms d...,tw_000000014
14,1222672687811702784,itdonafifi,franᶜʳᶠ,🇧🇷,929,Sat Oct 01 23:59:58 +0000 2022,Flamengo venceu\nAmanhã Lewis Hamilton vence\n...,0,1,pt,[],Twitter for Android,flamengo venceu amanhã lewis hamilton vence lu...,Flamengo venceu Amanhã Lewis Hamilton vence Lu...,tw_000000015
15,554544057,EstranhoDemais1,Ligado,NaN,91,Sat Oct 01 23:59:58 +0000 2022,"@Marisete1982 @Fa1ryNight A luta é constante, ...",0,3,pt,[],Twitter for Android,"@marisete1982 @fa1rynight a luta é constante, ...","@USER @USER A luta é constante , mas venceremo...",tw_000000016
16,1557140892569534464,riosvida6,+ 1,NaN,503,Sat Oct 01 23:59:58 +0000 2022,Porque votar em Jair Bolsonaro neste domingo h...,0,0,pt,[],Twitter Web App,porque votar em jair bolsonaro neste domingo h...,Porque votar em Jair Bolsonaro neste domingo H...,tw_000000017
17,1487530433055272964,be_caarol,Carol Bezerra,NaN,20,Sat Oct 01 23:59:58 +0000 2022,Não quero votar nem no lula nem no bozo,0,0,pt,[],Twitter for iPhone,não quero votar nem no lula nem no bozo,Não quero votar nem no lula nem no bozo,tw_000000018
18,279806528,kleber_1968,Lula Sempre #Vote13🚩,"Rio de Janeiro, Brasil",1449,Sat Oct 01 23:59:58 +0000 2022,LULA PRESIDENTE AMANHÃ!\nLULA NO PRIMEIRO TURN...,1,2,pt,"['LulaNo1ºTurno', 'LulaEoPTtudoNoPrimeiroTurno']",Twitter for Android,lula presidente amanhã! lula no primeiro turno...,LULA PRESIDENTE AMANHÃ ! LULA NO PRIMEIRO TURN...,tw_000000019
19,928067879056101377,wendpereira_,Wend ᶜʳᶠ,caxias city • crf,522,Sat Oct 01 23:59:58 +0000 2022,@guil_gabriel @ettorcidamemo quem apoia o cand...,0,0,pt,[],Twitter for Android,@guil_gabriel @ettorcidamemo quem apoia o cand...,@USER @USER quem apoia o candidato contrario t...,tw_000000020
20,865377026026373121,joecripto,joecripto,NaN,41,Sat Oct 01 23:59:58 +0000 2022,"@FilipeRet Cara, cada vez que vejo o eleitorad...",0,3,pt,[],Twitter Web App,"@filiperet cara, cada vez que vejo o eleitorad...","@USER Cara , cada vez que vejo o eleitorado do...",tw_000000021
21,1076576983180607489,conservadorRafa,Rafael Gomes. רָפָאֵל,"Recife, Brasil",211,Sat Oct 01 23:59:58 +0000 2022,@OliverStuenkel Botando o maior ladrão da hist...,0,0,pt,[],Twitter for iPhone,@oliverstuenkel botando o maior ladrão da hist...,@USER Botando o maior ladrão da história do Br...,tw_000000022
22,1565472553086361600,DosopalaRichard,Rico Richard DosOpala,"Rio de Janeiro, Brasil",75,Sat Oct 01 23:59:57 +0000 2022,@jairbolsonaro Esperamos que o senhor tenha um...,0,2,pt,[],Twitter for Android,@jairbolsonaro esperamos que o senhor tenha um...,@USER Esperamos que o senhor tenha um bom plan...,tw_000000023
23,151722541,AntonioCarlos__,Antonio Carlos .'.,Arapiraca - AL,446,Sat Oct 01 23:59:57 +0000 2022,Amanhã votarei no #Lula. Já aprendi a não desp...,0,4,pt,['Lula'],Twitter for Android,amanhã votarei no #lula. já aprendi a não desp...,Amanhã votarei no #Lula . Já aprendi a não des...,tw_000000024
24,1241149314824626179,gbicalhow,Embaixadora 🦑+🌵=❤️🇧🇷,NaN,2011,Sat Oct 01 23:59:57 +0000 2022,LeBron James fez o L. Eu desmaio se o @LewisHa...,3,13,pt,[],Twitter for Android,lebron james fez o l. eu desmaio se o @lewisha...,LeBron James fez o L . Eu desmaio se o @USER f...,tw_000000025
25,1563854314644406275,Mariade13075576,Maria de Fátima,NaN,51,Sat Oct 01 23:59:57 +0000 2022,@DarlitonSilva Será O dia\n...Lula no primeiro...,0,1,pt,[],Twitter for Android,@darlitonsilva será o dia ...lula no primeiro ...,@USER Será O dia ... Lula no primeiro turnoooo,tw_000000026
26,499912209,rbdpaixao,sarinha jurídico lula,"rbd, ddl, 1d, lm + multifandom",5723,Sat Oct 01 23:59:57 +0000 2022,@Naiarazevedo não gosta de política HOJE mas n...,0,4,pt,[],Twitter for iPhone,@naiarazevedo não gosta de política hoje mas n...,@USER não gosta de política HOJE mas no dia qu...,tw_000000027
27,1560796423003799552,higashrkata,🐀,"20 anos, qualquer pronome",43,Sat Oct 01 23:59:57 +0000 2022,lula com 54% tao deixando a gente sonhar,0,0,pt,[],Twitter for Android,lula com 54% tao deixando a gente sonhar,lula com 54 % tao deixando a gente sonhar,tw_000000028
28,1194092369207013377,MaciaVinicius,Vinicius Macía,"Mococa, Brasil",12,Sat Oct 01 23:59:57 +0000 2022,Usando a rejeição de Simone Tebet no datafolha...,0,0,pt,[],Twitter for Android,usando a rejeição de simone tebet no datafolha...,Usando a rejeição de Simone Tebet no datafolha...,tw_000000029
29,1475445151040483329,pedromanicongo,Pedro Mendes,"niterói, rio de janeiro",102,Sat Oct 01 23:59:57 +0000 2022,@marcelopjs há militares capazes de reestabele...,0,0,pt,[],Twitter Web App,@marcelopjs há militares capazes de reestabele...,@USER há militares capazes de reestabelecer a ...,tw_000000030
30,1500300117970198530,Marciapedrosob,Marcia Aparecida Pedroso Barreto,NaN,99,Sat Oct 01 23:59:57 +0000 2022,Boa ideia!!! \n51⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️\n\...,1,2,pt,[],Twitter for iPhone,boa ideia!!! 51⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️ lula...,Boa ideia ! ! ! 51 :estrela_branca_média: :est...,tw_000000031
31,1258855858043326466,veriatas_rerun,Wesley Silva,NaN,338,Sat Oct 01 23:59:57 +0000 2022,@LulaOficial é bolsonaro no primeiro turno e p...,0,0,pt,[],Twitter Web App,@lulaoficial é bolsonaro no primeiro turno e p...,@USER é bolsonaro no primeiro turno e ponto final,tw_000000032
32,39616592,Naaatchy," Que tistreza,",Brasil,333,Sat Oct 01 23:59:57 +0000 2022,Eu sei podre de todo mundo do meu Instagram qu...,0,2,pt,[],Twitter for Android,eu sei podre de todo mundo do meu instagram qu...,Eu sei podre de todo mundo do meu Instagram qu...,tw_000000033
33,171979494,CID_LUIS,CID LUÍS O. PINTO,CAMPINAS SP,353,Sat Oct 01 23:59:57 +0000 2022,@J_LIVRES ALERTA DE POSICIONAMENTO\nSó queria ...,0,0,pt,[],Twitter for iPhone,@j_livres alerta de posicionamento só queria d...,@USER ALERTA DE POSICIONAMENTO Só queria dizer...,tw_000000034
34,1523085205749256192,Eduardobez1977,Eduardo Bezerra,NaN,13,Sat Oct 01 23:59:57 +0000 2022,@direitasiqueira LULA PRESIDENTE AMANHA,1,3,pt,[],Twitter for Android,@direitasiqueira lula presidente amanha,@USER LULA PRESIDENTE AMANHA,tw_000000035
35,1202964167927443456,mpaulamelos,Paula 🇧🇷,"Montalvânia, Brasil",120,Sat Oct 01 23:59:57 +0000 2022,@L_felipebaliza do lula se deus quiser,0,1,pt,[],Twitter for iPhone,@l_felipebaliza do lula se deus quiser,@USER do lula se deus quiser,tw_000000036
36,1045038070230396928,DeHelci,Helci Ana,"Pituba, Salvador",8,Sat Oct 01 23:59:57 +0000 2022,@LulaOficial Bolsonaro será eleito,0,0,pt,[],Twitter for iPhone,@lulaoficial bolsonaro será eleito,@USER Bolsonaro será eleito,tw_000000037
37,2997884603,_Osnt_,Orlando Simões ⚜️,"Fortaleza, CE - Brasil",153,Sat Oct 01 23:59:57 +0000 2022,@TorresBetotada @PaulinhoSerra Estudou pra ach...,0,1,pt,[],Twitter for iPhone,@torresbetotada @paulinhoserra estudou pra ach...,@USER @USER Estudou pra achar que a OLIGARQUIA...,tw_000000038
38,1252370782124232704,JANI_VALVERD,"Jani valverde🤩♥️🚩❣️🚩⭐Petista é lulapetista🤩,.",Brasil,42876,Sat Oct 01 23:59:57 +0000 2022,@Belzebu__666 @ciro_nogueira Nem sei se dormir...,0,2,pt,[],Twitter for Android,@belzebu__666 @ciro_nogueira nem sei se dormir...,"@USER @USER Nem sei se dormirei , a ansiedade ...",tw_000000039
39,2738518035,ThadeuPenido,Thadeu Penido CAM,"Minas Gerais, Brasil",10867,Sat Oct 01 23:59:56 +0000 2022,"@ThiagoResiste LULA PRESIDENTE AMANHÃ,JÁ PASS...",1,2,pt,[],Twitter for Android,"@thiagoresiste lula presidente amanhã,já passo...","@USER LULA PRESIDENTE AMANHÃ , JÁ PASSOU DE 20...",tw_000000040
40,137148495,luisgrimaldi9,@LuisGrimaldi9 @telenueve @Canal9,Buenos Aires Argentina,4139,Sat Oct 01 23:59:56 +0000 2022,@jairbolsonaro ele vai dançar tão mal mas elev...,0,0,pt,[],Twitter for Android,@jairbolsonaro ele vai dançar tão mal mas elev...,@USER ele vai dançar tão mal mas elevou o país...,tw_000000041
41,2829734034,JuridicoRodrigo,Rodrigo Neves,NaN,192,Sat Oct 01 23:59:56 +0000 2022,@mvitorodrigues @Estadao Rejeição do Bolsonaro...,0,0,pt,[],Twitter for iPhone,@mvitorodrigues @estadao rejeição do bolsonaro...,@USER @USER Rejeição do Bolsonaro diminuindo e...,tw_000000042
42,1562969951408861184,zeguilherme63,zeguilherme,NaN,1,Sat Oct 01 23:59:56 +0000 2022,@ThiagoResiste LULA PRESIDENTE AMANHÃ!\nDEMOCR...,2,5,pt,[],Twitter for Android,@thiagoresiste lula presidente amanhã! democra...,@USER LULA PRESIDENTE AMANHÃ ! DEMOCRACIA SEMP...,tw_000000043
43,1302265014687072256,eva_cmendez,Eva Mendez,"São Paulo, Brasil",87,Sat Oct 01 23:59:56 +0000 2022,O Lula podia ganhar com 51% em homenagem a tod...,2,9,pt,[],Twitter for iPhone,o lula podia ganhar com 51% em homenagem a tod...,O Lula podia ganhar com 51 % em homenagem a to...,tw_000000044
44,1353016828835078145,ogthuzzy,neguin chei d´odio #BlackLivesMatter,NaN,31,Sat Oct 01 23:59:56 +0000 2022,minha prima e maconheira e vai vota no Bolsona...,0,0,pt,[],Twitter for Android,minha prima e maconheira e vai vota no bolsona...,minha prima e maconheira e vai vota no Bolsona...,tw_000000045
45,1305470686316711936,OOpinadorPessi1,Opinião Agora #ANTIPT #22,NaN,7,Sat Oct 01 23:59:56 +0000 2022,"É o recado para vocês, eleitores de Lula! É 22...",0,0,pt,[],Twitter Web App,"é o recado para vocês, eleitores de lula! é 22...","É o recado para vocês , eleitores de Lula ! É ...",tw_000000046
46,558223548,_LittleBri,plebeu da Rhaenyra,"Rio de Janeiro, Brasil",174,Sat Oct 01 23:59:56 +0000 2022,acho que os professores deviam cancelar as aul...,1,2,pt,[],Twitter Web App,acho que os professores deviam cancelar as aul...,acho que os professores deviam cancelar as aul...,tw_000000047
47,3322117329,triwdade,ligia LULA 13 ⭐,"Campina Grande, Brasil",846,Sat Oct 01 23:59:56 +0000 2022,"eu assim com voinha, cheguei na farmácia com e...",0,1,pt,[],Twitter for iPhone,"eu assim com voinha, cheguei na farmácia com e...","eu assim com voinha , cheguei na farmácia com ...",tw_000000048
48,1541427273299025923,wolfshaushiler,My Rebel Machine 🚩,"Blumenau, Brasil",4,Sat Oct 01 23:59:56 +0000 2022,@ThiagoResiste LULA PRESIDENTE AMANHÃ!!! ❤️❤️❤...,1,7,pt,[],Twitter for iPhone,@thiagoresiste lula presidente amanhã!!! ❤️❤️❤...,@USER LULA PRESIDENTE AMANHÃ ! ! ! :coração_ve...,tw_000000049
49,1378487211310600192,jjkgalaxyes,ɓɛʆʆɑ🍒°• 📖: Kingdom Of The Cursed / I LOVE 💔,"Velaris, Corte dos Sonhos 🌌",287,Sat Oct 01 23:59:56 +0000 2022,@elysamotaa5 @Ravienaoficial @GulinelliRose @r...,0,3,pt,[],Twitter for Android,@elysamotaa5 @ravienaoficial @gulinellirose @r...,"@USER @USER @USER @USER Era o Bolsonaro , ELE ...",tw_000000050